spring.application.name=email-writer

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=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
groq.model=llama-3.3-70b-versatile
server.port=8081